# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'upwork-project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for upwork-project
  pod 'MapboxMaps', '~> 11.0'

  target 'upwork-projectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'upwork-projectUITests' do
    # Pods for testing
  end

end

# Workaround for rsync issues with Mapbox
install! 'cocoapods', 
  :deterministic_uuids => false

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      
      # Fix for Apple Silicon Macs - ensure proper architecture support
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      
      # Don't exclude arm64 for simulator - this was causing the issue
      config.build_settings.delete('EXCLUDED_ARCHS[sdk=iphonesimulator*]')
      
      # Disable bitcode for compatibility
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # Code signing fixes
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      
      # Fix sandbox/permissions issues
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
      
      # Framework search paths
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << '$(BUILT_PRODUCTS_DIR)'
      
      # Fix for rsync issues
      config.build_settings.delete('SWIFT_SERIALIZE_DEBUGGING_OPTIONS')
      config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
    end
  end
end
